# Generated by Django 5.0.3 on 2024-06-09 12:55

import cars.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=cars.models.brand_directory_path)),
                ('car_model', models.CharField(max_length=150)),
                ('qountity', models.IntegerField()),
                ('describtion', models.TextField()),
                ('price', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='brands.brand')),
            ],
        ),
    ]
