# Generated by Django 5.0.3 on 2024-06-10 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='qountity',
            new_name='quantity',
        ),
    ]
