# Generated by Django 5.0.3 on 2024-06-10 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_qountity_car_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brand',
            new_name='brands',
        ),
    ]
