# Generated by Django 5.0.3 on 2024-06-10 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_brand_car_brands'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brands',
            new_name='brand',
        ),
    ]
