# Generated by Django 5.0.3 on 2024-06-12 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_comment_date_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='car',
        ),
    ]
