# Generated by Django 5.0.3 on 2024-06-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qountity', models.IntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
                ('car', models.ManyToManyField(to='cars.car')),
            ],
        ),
    ]
